//there are two predefined users (id: 1, id: 2) in the application
//for which orders can be placed

//create new transaction for customer
POST http://localhost:8080/api/order
Accept: application/json
Content-Type: application/json

{
"customerId": 1,
"entries": [
  {
    "name": "Product 1",
    "price": 90
  },
  {
    "name": "Product 2",
    "price": 30
  }
],
  "transactionDate": "2022-08-25T21:34:55"
}

###
//get points data for customer based on id
GET http://localhost:8080/api/reward/1
Accept: application/json
Content-Type: application/json

###
//get points data for all users
GET http://localhost:8080/api/reward
Accept: application/json
Content-Type: application/json

###
//transaction update
//create new transaction for customer
PATCH http://localhost:8080/api/order/13
Accept: application/json
Content-Type: application/json

{
  "entries": [
    {
      "name": "Product 1",
      "price": 20
    },
    {
      "name": "Product 2",
      "price": 50
    }
  ],
  "transactionDate": "2022-08-30T21:34:55"
}


###
//rest exception handler example
POST http://localhost:8080/api/order
Accept: application/json
Content-Type: application/json

{
"customerId": 5,
"entries": [
{
"name": "Product 1",
"price": 40
},
{
"name": "Product 2",
"price": 24
}
],
"transactionDate": "2022-08-25T21:34:55"
}